#!/bin/bash
clear
echo "El número de parámetros introducidos es: $#."
echo "Los parámetros introducidos son (*): $*"
echo "Los parámetros introducidos son (@): $@"
echo "El nombre del script es: $0"
echo "Primer parametro: $1"
echo "Resultado de la instrucción anterior: $?"
echo "Segundo parámetro: $2"
echo "Tercer parámetro: $3"
echo "PID: $$"
echo "ENVIROMENT VARIABLES"
echo "HOME: $HOME"
echo "USER: $USER"
echo "Path Work Directory: $PWD"
echo "Previous Path Work Directory: $OLDPWD"
echo "PATH: $PATH"
echo "IFS: $IFS"
echo "MyVar: ${MyVar:=$1}"
echo "MyVar: ${MyVar:-nothing}"
